import { Container, Grid } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from './About'
import Contact from './Contact'
import Education from './Education'
import Experiance from './Experiance'
import Hobbies from './Hobbies'
import Name from './Name'
import Skills from './Skills'
import Social from './Social'
import Tools from './Tools'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{padding:"16px"}}>
      <Grid container spacing={5} >
        <Grid xs={12} item>
          <Name/>
        </Grid>
        <Grid xs={12} item>
        <About/>
        </Grid>
        <Grid xs={12} item>
        <Education/>
        </Grid>
        <Grid xs={12} item>
        <Experiance/>
        </Grid>
        <Grid xs={12} item>
        <Skills/>
        </Grid>
        <Grid xs={12} item>
        <Tools/>
        </Grid>
        <Grid xs={12} item>
        <Hobbies/>
        </Grid>
        <Grid xs={12} item>
        <Contact/>
        </Grid>
        <Grid xs={12} item>
        <Social/>
        </Grid>
      </Grid>
      </Container>
    </div>
  )
}
